### ISSUE TITLE
windows x64 empty zip

### ISSUE THREAD

**Issue by Jaen-Minetest** [atsb/freelarn#2]
the windows x64 zip extracts to an unplayable empty folder. there is only one file in the bin folder called stub and the docs folder has changelog, history and license. there is no windows excutable in that zip, no way to play it..

**Comment by atsb** [comment]
Well that's a mistake!  I did the release late at night and Windows isn't my main platform so I guess I completely missed that!

I will generate a new binary today and upload it.  I should have spotted it as the download is only 50kb..  thanks a lot!

**Comment by atsb** [comment]
Fixed now, enjoy it :)
