### ISSUE TITLE
Running not supported?

### ISSUE THREAD

**Issue by 0branch** [atsb/freelarn#4]
`B`, `H`, `J`, `K`, `L`, `N`, `U` and `Y` are documented but seemingly unsupported: I can't find any reference to them in [parse](https://github.com/atsb/freelarn/blob/master/src/core/FLArgParsing.cpp#L39). Planned for a later release?

For reference, here's an excerpt from the current help screen:

```
b  move southwest          B  run southwest            A  desecrate an altar
...
h  move left               H  run left                    volcanic shaft    
i  inventory your pockets  I  list all known items                            
j  move down               J  run down                 ^  identify a trap    
k  move up                 K  run up                   ,  pick up object        
l  move right              L  run right                :  look at object you
n  move southeast          N  run southeast               are standing on    
...
u  move northeast          U  run northeast                                    
...
y  move northwest          Y  run northwest            ^L redraw the screen    
```

**Comment by 0branch** [comment]
(From your `larn` repo: '[H](https://github.com/atsb/larn/blob/master/main.c#L426)', [run]( 
https://github.com/atsb/larn/blob/master/main.c#L807-L818).)

**Comment by atsb** [comment]
This is correct, Running will be done in a later release.  Though I will fix this soon and release something.

**Comment by atsb** [comment]
New release fixes it.
